project:
  title: "Лабораторная работа № 7"
  output-dir: "_output"
standalone: true
self-contained: true
slide-level: 2
lang: ru-RU
format:
  beamer:
    toc: true
    toc-title: Содержание
    aspectratio: 169
    section-titles: true
    incremental: false
    colorlinks: false
    include-in-header:
      - file: _resources/tex/beamer.tex
    babel-lang: russian
    babel-otherlangs: english
  revealjs:
    transition: slide
    margin: 0.12
    smaller: true
    slide-number: true
    output-ext: html
    theme: white
    css: styles.css
    logo: ../image/brand/logo-rudn.png
