project:
  title: "Лабораторная работа № 1"
  output-dir: "_output"

lang: ru-RU
format:
  revealjs:
    embed-resources: true
    slide-number: true
    transition: fade
    background-transition: none
    width: 1280
    height: 720
    margin: 0.12
    center: true
    controls: true
    progress: true
    smaller: true
    theme: simple
    logo: ../image/brand/university-mark.png
    css: styles.css
